In [1]:
import numpy as np

In [2]:
myList = [2,4,6]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([2, 4, 6])

In [7]:
myArr = np.array(myList)
type(myArr)

numpy.ndarray

In [6]:
myList

[2, 4, 6]

## 2-D array 

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
a.ndim
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

2

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

**.arange()**

In [36]:
np.arange(0,10,2)

# not including the end

array([0, 2, 4, 6, 8])

**.zeros()**

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
a = np.zeros((2,4))
# the first number is rows
# the second number is column

In [30]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
a.ndim

2

**.ones()**

In [32]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**.linspace**

In [34]:
np.linspace(0,10,3)

# the first number is start
# the second number is including end
# the third number is the evenly spaced number

array([ 0.,  5., 10.])

In [35]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

**.eye()**

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random

In [38]:
np.random.rand(1)

array([0.26882077])

In [40]:
np.random.rand(3,4)

array([[0.94459993, 0.71490558, 0.58910042, 0.69408507],
       [0.39436261, 0.27157342, 0.72598746, 0.96538816],
       [0.35945469, 0.3448795 , 0.63310174, 0.72300876]])

In [43]:
np.random.randn(10)

# standard normal distribution

array([-0.72509175, -0.42549083, -0.17862745, -0.80210979, -1.28956496,
       -1.04778558, -0.12255598,  0.20354896, -1.56867974,  0.04528769])

In [42]:
np.random.randn(5,2)

array([[-0.93515351, -0.44630445],
       [ 0.38945514,  0.28380677],
       [ 0.86354377,  0.82538767],
       [-0.30843182, -1.6588732 ],
       [-0.98568309,  0.6903787 ]])

In [44]:
np.random.randint(0,100,5)

array([39, 66, 91, 80, 90])

In [45]:
np.random.randint(0,100,(4,5))

array([[94, 24, 18, 24, 23],
       [90, 25, 84, 84,  6],
       [24, 45, 71, 95, 29],
       [65, 39, 34, 13, 68]])

In [46]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [47]:
arr = np.arange(0,24)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
randArr = np.random.randint(0,100,10)

In [52]:
randArr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [53]:
randArr.max()

87

In [54]:
randArr.min()

1

In [55]:
randArr.argmax()

# index of the max in array

1

In [57]:
randArr.argmin()

# index of the min in array

0

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
arr.shape

(24,)

In [65]:
arr = arr.reshape(6,4)

In [66]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
arr.shape

(6, 4)