In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

In [5]:
arr[2:5]

array([2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 200

In [15]:
arr

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [19]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_array = arr[:5]

In [21]:
slice_of_array

array([0, 1, 2, 3, 4])

In [22]:
slice_of_array[:] = 200

In [23]:
slice_of_array

array([200, 200, 200, 200, 200])

In [24]:
arr

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [25]:
# to avoid changing in main array you can make a copy

arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr_copy = arr.copy()

In [28]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr_copy[:] = 200

In [30]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr_2d.shape

(3, 3)

In [36]:
arr_2d[0]

# grab row 1

array([1, 2, 3])

In [37]:
arr_2d[2,2]

# row 2 and column 2

9

In [39]:
arr_2d[1,0]

# row 1 and column 0

4

In [40]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

**in real datasets, rows stand for data points**
**and columns stand for features**

In [47]:
arr = np.arange(1,11)

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
bool_arr = arr>4

In [51]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [53]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
# OR :)

arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])