In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr - 6

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
1 / arr

# in numpy it gives warning when dividing 1 to 0
# but in python it gives error
# inf stand for infinity

C:\Users\Chalus System\AppData\Local\Temp\ipykernel_280\661540703.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [21]:
np.log(arr)

C:\Users\Chalus System\AppData\Local\Temp\ipykernel_280\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr.sum()

55

In [24]:
arr.mean()

5.0

In [25]:
arr.max()

10

In [28]:
arr.min()

0

In [26]:
arr.var()
# variance

10.0

In [27]:
arr.std()
#standard deviation

3.1622776601683795

In [35]:
arr_2d = np.arange(0,20).reshape(5,4)

In [36]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
arr_2d.shape

(5, 4)

In [38]:
arr_2d.sum()

190

In [39]:
arr_2d.sum(axis = 0)

# sum the columns

array([40, 45, 50, 55])

In [40]:
arr_2d.sum(axis = 1)

# sum the rows

array([ 6, 22, 38, 54, 70])